#!/bin/bash

# Build script for Narzędzia Sukcesu the logotype font
# Copyright 2012 Grzegorz Rolek


# Make sure the tools are available.
for TOOL in ftxdumperfuser ftxenhancer makeotf
do type $TOOL &>/dev/null || { echo >&2 "Fatal: Make sure you have OS X Font Tools and Adobe's FDK installed."; exit 1; }
done

# Clean up existing builds, if any.
rm -rf build && mkdir build

# Prepare the target for compilation.
TARGET=build/NarzedziaSukcesu.ttf
cp Null.ttf $TARGET

# Now compile. Note the table order, it's imporant.
# First fuse the basic required stuff.
for TABLE in head name maxp glyf cmap hmtx hhea post
do ftxdumperfuser --datafile $TABLE.xml --table $TABLE $TARGET
done

# Include the morph table.
ftxenhancer --mif morphing.mif $TARGET

# State machine kerning as generic hex data.
for TABLE in kern
do ftxdumperfuser --datafile $TABLE.xml --generic --table $TABLE $TARGET
done

# Compile the OpenType Layout features.
makeotf -f $TARGET -o ${TARGET%.ttf}.otf -ff features.fea
mv ${TARGET%.ttf}.otf $TARGET

# Remove the 'OS/2' table generated by the makeotf compiler.
ftxdumperfuser --kill-table --table 'OS/2' $TARGET

# Bring back original forms of the tables modified by the makeotf.
for TABLE in head name cmap hhea post
do ftxdumperfuser --datafile $TABLE.xml --table $TABLE $TARGET
done

# Clean up after the makeotf.
rm build/current.fpr

# Treat the final font with an autohinter, if available.
if type ttfautohint &>/dev/null
then

	# Make a temporary move just to have a path to make a hinting from.
	TMP_TARGET=build/$(basename -s .ttf $TARGET)_unhinted.ttf
	mv $TARGET $TMP_TARGET

	# Do the autohinting.
	ttfautohint --latin-fallback --no-info $TMP_TARGET $TARGET

	# Clean up.
	rm $TMP_TARGET

else echo >&2 "Note: The 'ttfautohint' wasn't found; the font hasn't been hinted."
fi

# That's it.
exit
